# -*- coding: utf-8 -*-
"""dummy_variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19FMxdMKF6ZVkbMCDhONv2hyPKRNuQDs2
"""

class MyDummyVariable:
  ohe_encoders = {}
  def __init__(self):
    pass
  
  def combined_dataset(self, features, categorical_ohe):
    import numpy as np
    #combine categorical_ohe and numeric columns
    numeric_data = features.select_dtypes(exclude = 'object').values
    
    #OneHotEncoded Data 
    ohe_data = np.concatenate([categorical_ohe, numeric_data], axis = 1)
    return ohe_data
  
  #fit transform
  def fit_transform(self, features):
    
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
    import numpy as np
    import pandas as pd
    categorical_data = features.select_dtypes(include = 'object')
    categorical_ohe = None
    for i in categorical_data.columns:
      ohe = OneHotEncoder(handle_unknown = 'ignore', sparse = False)
      encoded_column = ohe.fit_transform(categorical_data[[i]].values)[:, 1:]
      MyDummyVariable.ohe_encoders[i] = ohe
      if categorical_ohe:
        categorical_ohe = np.concatenate([categorical_ohe, encoded_columns], axis = 1)
      else:
        categorical_ohe = encoded_column
        
      return self.combined_dataset(features, categorical_ohe)
  
  
  
  def transform(self, features):
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
    import numpy as np
    import pandas as pd
    categorical_data = features.select_dtypes(include = 'object')
    categorical_ohe = None
    for i in categorical_data.columns:
      encoded_column = MyDummyVariable.ohe_encoders[i].transform(categorical_data[[i]].values)[:, 1:]
      
      if categorical_ohe:
        categorical_ohe = np.concatenate([categorical_ohe, encoded_columns], axis = 1)
      else:
        categorical_ohe = encoded_column
        
      return self.combined_dataset(features, categorical_ohe)

